# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bits and Blocks
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  At Bits and Blocks we showcase networks built on blockchain technology.
  Applications controlling assets with distributed transactions are examined.
  Mandarin speakers and English speakers are welcome to experience a free
  blockchain workshop for beginners in the Bits and Blocks village.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
