# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bits and Blocks
email: staff@bitsblocks.org
description: > # this means to ignore newlines until "baseurl:"
  At Bits and Blocks we showcase networks built on blockchain technology.
  Applications controlling assets with distributed transactions are examined.
  Mandarin speakers and English speakers are welcome to experience a free
  blockchain workshop for beginners in the Bits and Blocks village.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.bitsblocks.org" # the base hostname & protocol for your site
twitter_username:
github_username:
google_analytics_key:

# Build settings
permalink: /:title  # disables post output
markdown: kramdown

# Template site wide CSS colors
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  grey:      '#a0a0b0'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  seacol:    '#486a89'
  redish:    '#e02000'
  orange:    '#fab125'
  salmon:    '#ed8050'
  turquoise: '#0fbfcf'

kramdown:
  auto_ids:  false

